### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by Swimmingman** [cjdduarte/Free_Weekend#2]
Great idea! However, it does not seem to work. Cards with >3d intervals still get assigned to my days off and it does not show a log info. Did I do anything wrong with the configuration?

{
"days_week": [],
"log_tooltip": 3,
"specific_days": [
"2019/05/01",
"2019/05/04",
"2019/05/05",
"2019/05/11",
"2019/05/12",
"2019/05/18",
"2019/05/19",
"2019/05/26",
"2019/05/25",
"2019/06/01",
"2019/05/02"
]
}

**Comment by cjdduarte** [comment]
Hi, the add-on does not reprogram cards already scheduled, it works the moment you respond to the cards.
Example: If you installed the addon today and there are already 20 cards scheduled for next Sunday, these cards will continue on this day. But the new cards that you start to study from today will not be scheduled for this day.
