### ISSUE TITLE
Free Weekend Add-on option for including step cards

### ISSUE THREAD

**Issue by ischumac** [cjdduarte/Free_Weekend#3]
1/20 - Realized why this is not working: it does not work with learning cards (aka cards with steps), but that is in the description. I spend more time than most people working on cards with steps because I have an extra layer of steps (my steps: 15 1440 5760), so those are the ones that need to be pushed away from my day off. This would be really helpful if it could be adjusted as such.

1/22 - To be fair, this add-on has more customizability than load-balancer alone and works well. I'll give it the thumbs up for that, but please put together an add-on that includes step cards.

**Comment by cjdduarte** [comment]
I use a similar configuration: 15 1440 8640.
I will investigate here, because I believe that Anki did not implement Fuzz natively in the role of learning cards. Confirming this, I will have to implement this function in my code.
Today I use an Anki function.

**Comment by ischumac** [comment]
How is enhancement coming? Could you also add a load balancer to this add-on?

**Comment by cjdduarte** [comment]
There is already a load-balanced version. You can find it here: https://github.com/cjdduarte/Free_Weekend_Load_Balancer

Related to the improvement, I am still evaluating. Anki does not use fuzz on learning cards by default, which is how I make the decision to relocate the card. I am evaluating how to insert without interfering with the learning algorithm.

**Comment by ischumac** [comment]
any luck yet? my learning cards are still causing problems like this one:

![image](https://user-images.githubusercontent.com/60202015/75689397-1e6ff380-5c6f-11ea-9922-74bfd9178df6.png)

**Comment by cjdduarte** [comment]
What is the doubt? Wouldn't those days be relocated?

![image](https://user-images.githubusercontent.com/42243532/75824192-d55c9400-5d81-11ea-9348-aae043fcff33.png)

**Comment by ischumac** [comment]
They should, but my step/learning cards are not being relocated? Have you figured out a way to load balance the step/learning cards as well?

**Comment by ischumac** [comment]
*have you Figured it out yet?

**Comment by cjdduarte** [comment]
I opened a support with Damien to include Fuzz in the learning cards. There is no such functionality and the change would be far beyond my knowledge. I'm also interested in that.

**Comment by corgilobacterjejuni** [comment]
If I wanted to not have cards on Saturday and Sunday do I enter: [5] or [5,6] or days of the week... [4]
the wording is a bit confusing to me and I couldn't find a solid example of that. Ty in advance.

**Comment by cjdduarte** [comment]
[5,6]

> If I wanted to not have cards on Saturday and Sunday do I enter: [5] or [5,6] or days of the week... [4]
> the wording is a bit confusing to me and I couldn't find a solid example of that. Ty in advance.

**Comment by corgilobacterjejuni** [comment]
> [5,6]
> 
> If I wanted to not have cards on Saturday and Sunday do I enter: [5] or [5,6] or days of the week... [4]
> the wording is a bit confusing to me and I couldn't find a solid example of that. Ty in advance.

thank you kindly for your time
